# Generated by Django 5.0.7 on 2024-07-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='KLAB',
            new_name='quantity',
        ),
    ]
